/* Copyright 2017 WALLIX

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// DO NOT EDIT
// This file was automatically generated with go generate
package awsspec

var APIPerTemplateDefName = map[string]string{
	"attachalarm":               "cloudwatch",
	"attachcontainertask":       "ecs",
	"attachelasticip":           "ec2",
	"attachinstance":            "elbv2",
	"attachinstanceprofile":     "ec2",
	"attachinternetgateway":     "ec2",
	"attachmfadevice":           "iam",
	"attachnetworkinterface":    "ec2",
	"attachpolicy":              "iam",
	"attachrole":                "iam",
	"attachroutetable":          "ec2",
	"attachsecuritygroup":       "ec2",
	"attachuser":                "iam",
	"attachvolume":              "ec2",
	"authenticateregistry":      "ecr",
	"checkcertificate":          "acm",
	"checkdatabase":             "rds",
	"checkdistribution":         "cloudfront",
	"checkinstance":             "ec2",
	"checkloadbalancer":         "elbv2",
	"checknatgateway":           "ec2",
	"checknetworkinterface":     "ec2",
	"checkscalinggroup":         "autoscaling",
	"checksecuritygroup":        "ec2",
	"checkvolume":               "ec2",
	"copyimage":                 "ec2",
	"copysnapshot":              "ec2",
	"createaccesskey":           "iam",
	"createalarm":               "cloudwatch",
	"createappscalingpolicy":    "applicationautoscaling",
	"createappscalingtarget":    "applicationautoscaling",
	"createbucket":              "s3",
	"createcertificate":         "acm",
	"createcontainercluster":    "ecs",
	"createdatabase":            "rds",
	"createdbsubnetgroup":       "rds",
	"createdistribution":        "cloudfront",
	"createelasticip":           "ec2",
	"createfunction":            "lambda",
	"creategroup":               "iam",
	"createimage":               "ec2",
	"createinstance":            "ec2",
	"createinstanceprofile":     "iam",
	"createinternetgateway":     "ec2",
	"createkeypair":             "ec2",
	"createlaunchconfiguration": "autoscaling",
	"createlistener":            "elbv2",
	"createloadbalancer":        "elbv2",
	"createloginprofile":        "iam",
	"createmfadevice":           "iam",
	"createnatgateway":          "ec2",
	"createnetworkinterface":    "ec2",
	"createpolicy":              "iam",
	"createqueue":               "sqs",
	"createrecord":              "route53",
	"createrepository":          "ecr",
	"createrole":                "iam",
	"createroute":               "ec2",
	"createroutetable":          "ec2",
	"creates3object":            "s3",
	"createscalinggroup":        "autoscaling",
	"createscalingpolicy":       "autoscaling",
	"createsecuritygroup":       "ec2",
	"createsnapshot":            "ec2",
	"createstack":               "cloudformation",
	"createsubnet":              "ec2",
	"createsubscription":        "sns",
	"createtag":                 "ec2",
	"createtargetgroup":         "elbv2",
	"createtopic":               "sns",
	"createuser":                "iam",
	"createvolume":              "ec2",
	"createvpc":                 "ec2",
	"createzone":                "route53",
	"deleteaccesskey":           "iam",
	"deletealarm":               "cloudwatch",
	"deleteappscalingpolicy":    "applicationautoscaling",
	"deleteappscalingtarget":    "applicationautoscaling",
	"deletebucket":              "s3",
	"deletecertificate":         "acm",
	"deletecontainercluster":    "ecs",
	"deletecontainertask":       "ecs",
	"deletedatabase":            "rds",
	"deletedbsubnetgroup":       "rds",
	"deletedistribution":        "cloudfront",
	"deleteelasticip":           "ec2",
	"deletefunction":            "lambda",
	"deletegroup":               "iam",
	"deleteimage":               "ec2",
	"deleteinstance":            "ec2",
	"deleteinstanceprofile":     "iam",
	"deleteinternetgateway":     "ec2",
	"deletekeypair":             "ec2",
	"deletelaunchconfiguration": "autoscaling",
	"deletelistener":            "elbv2",
	"deleteloadbalancer":        "elbv2",
	"deleteloginprofile":        "iam",
	"deletemfadevice":           "iam",
	"deletenatgateway":          "ec2",
	"deletenetworkinterface":    "ec2",
	"deletepolicy":              "iam",
	"deletequeue":               "sqs",
	"deleterecord":              "route53",
	"deleterepository":          "ecr",
	"deleterole":                "iam",
	"deleteroute":               "ec2",
	"deleteroutetable":          "ec2",
	"deletes3object":            "s3",
	"deletescalinggroup":        "autoscaling",
	"deletescalingpolicy":       "autoscaling",
	"deletesecuritygroup":       "ec2",
	"deletesnapshot":            "ec2",
	"deletestack":               "cloudformation",
	"deletesubnet":              "ec2",
	"deletesubscription":        "sns",
	"deletetag":                 "ec2",
	"deletetargetgroup":         "elbv2",
	"deletetopic":               "sns",
	"deleteuser":                "iam",
	"deletevolume":              "ec2",
	"deletevpc":                 "ec2",
	"deletezone":                "route53",
	"detachalarm":               "cloudwatch",
	"detachcontainertask":       "ecs",
	"detachelasticip":           "ec2",
	"detachinstance":            "elbv2",
	"detachinstanceprofile":     "ec2",
	"detachinternetgateway":     "ec2",
	"detachmfadevice":           "iam",
	"detachnetworkinterface":    "ec2",
	"detachpolicy":              "iam",
	"detachrole":                "iam",
	"detachroutetable":          "ec2",
	"detachsecuritygroup":       "ec2",
	"detachuser":                "iam",
	"detachvolume":              "ec2",
	"importimage":               "ec2",
	"startalarm":                "cloudwatch",
	"startcontainertask":        "ecs",
	"startdatabase":             "rds",
	"startinstance":             "ec2",
	"stopalarm":                 "cloudwatch",
	"stopcontainertask":         "ecs",
	"stopdatabase":              "rds",
	"stopinstance":              "ec2",
	"updatebucket":              "s3",
	"updatecontainertask":       "ecs",
	"updatedistribution":        "cloudfront",
	"updateimage":               "ec2",
	"updateinstance":            "ec2",
	"updateloginprofile":        "iam",
	"updatepolicy":              "iam",
	"updaterecord":              "route53",
	"updates3object":            "s3",
	"updatescalinggroup":        "autoscaling",
	"updatesecuritygroup":       "ec2",
	"updatestack":               "cloudformation",
	"updatesubnet":              "ec2",
	"updatetargetgroup":         "elbv2",
}

var AWSTemplatesDefinitions = map[string]Definition{
	"attachalarm": {
		Action:         "attach",
		Entity:         "alarm",
		Api:            "cloudwatch",
		RequiredParams: []string{},
		ExtraParams:    []string{"action-arn", "name"},
	},
	"attachcontainertask": {
		Action:         "attach",
		Entity:         "containertask",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"command", "container-name", "env", "image", "memory-hard-limit", "name", "ports", "privileged", "workdir"},
	},
	"attachelasticip": {
		Action:         "attach",
		Entity:         "elasticip",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"allow-reassociation", "id", "instance", "networkinterface", "privateip"},
	},
	"attachinstance": {
		Action:         "attach",
		Entity:         "instance",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "port", "targetgroup"},
	},
	"attachinstanceprofile": {
		Action:         "attach",
		Entity:         "instanceprofile",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"instance", "name", "replace"},
	},
	"attachinternetgateway": {
		Action:         "attach",
		Entity:         "internetgateway",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "vpc"},
	},
	"attachmfadevice": {
		Action:         "attach",
		Entity:         "mfadevice",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "mfa-code-1", "mfa-code-2", "no-prompt", "user"},
	},
	"attachnetworkinterface": {
		Action:         "attach",
		Entity:         "networkinterface",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"device-index", "id", "instance"},
	},
	"attachpolicy": {
		Action:         "attach",
		Entity:         "policy",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"access", "arn", "group", "role", "service", "user"},
	},
	"attachrole": {
		Action:         "attach",
		Entity:         "role",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"instanceprofile", "name"},
	},
	"attachroutetable": {
		Action:         "attach",
		Entity:         "routetable",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "subnet"},
	},
	"attachsecuritygroup": {
		Action:         "attach",
		Entity:         "securitygroup",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "instance"},
	},
	"attachuser": {
		Action:         "attach",
		Entity:         "user",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"group", "name"},
	},
	"attachvolume": {
		Action:         "attach",
		Entity:         "volume",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"device", "id", "instance"},
	},
	"authenticateregistry": {
		Action:         "authenticate",
		Entity:         "registry",
		Api:            "ecr",
		RequiredParams: []string{},
		ExtraParams:    []string{"accounts", "no-confirm", "no-docker-login"},
	},
	"checkcertificate": {
		Action:         "check",
		Entity:         "certificate",
		Api:            "acm",
		RequiredParams: []string{},
		ExtraParams:    []string{"arn", "state", "timeout"},
	},
	"checkdatabase": {
		Action:         "check",
		Entity:         "database",
		Api:            "rds",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"checkdistribution": {
		Action:         "check",
		Entity:         "distribution",
		Api:            "cloudfront",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"checkinstance": {
		Action:         "check",
		Entity:         "instance",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"checkloadbalancer": {
		Action:         "check",
		Entity:         "loadbalancer",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"checknatgateway": {
		Action:         "check",
		Entity:         "natgateway",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"checknetworkinterface": {
		Action:         "check",
		Entity:         "networkinterface",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"checkscalinggroup": {
		Action:         "check",
		Entity:         "scalinggroup",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"count", "name", "timeout"},
	},
	"checksecuritygroup": {
		Action:         "check",
		Entity:         "securitygroup",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"checkvolume": {
		Action:         "check",
		Entity:         "volume",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "state", "timeout"},
	},
	"copyimage": {
		Action:         "copy",
		Entity:         "image",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"description", "encrypted", "name", "source-id", "source-region"},
	},
	"copysnapshot": {
		Action:         "copy",
		Entity:         "snapshot",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"description", "encrypted", "source-id", "source-region"},
	},
	"createaccesskey": {
		Action:         "create",
		Entity:         "accesskey",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"save", "user"},
	},
	"createalarm": {
		Action:         "create",
		Entity:         "alarm",
		Api:            "cloudwatch",
		RequiredParams: []string{},
		ExtraParams:    []string{"alarm-actions", "description", "dimensions", "enabled", "evaluation-periods", "insufficientdata-actions", "metric", "name", "namespace", "ok-actions", "operator", "period", "statistic-function", "threshold", "unit"},
	},
	"createappscalingpolicy": {
		Action:         "create",
		Entity:         "appscalingpolicy",
		Api:            "applicationautoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"dimension", "name", "resource", "service-namespace", "stepscaling-adjustment-type", "stepscaling-adjustments", "stepscaling-aggregation-type", "stepscaling-cooldown", "stepscaling-min-adjustment-magnitude", "type"},
	},
	"createappscalingtarget": {
		Action:         "create",
		Entity:         "appscalingtarget",
		Api:            "applicationautoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"dimension", "max-capacity", "min-capacity", "resource", "role", "service-namespace"},
	},
	"createbucket": {
		Action:         "create",
		Entity:         "bucket",
		Api:            "s3",
		RequiredParams: []string{},
		ExtraParams:    []string{"acl", "name"},
	},
	"createcertificate": {
		Action:         "create",
		Entity:         "certificate",
		Api:            "acm",
		RequiredParams: []string{},
		ExtraParams:    []string{"domains", "validation-domains"},
	},
	"createcontainercluster": {
		Action:         "create",
		Entity:         "containercluster",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"createdatabase": {
		Action:         "create",
		Entity:         "database",
		Api:            "rds",
		RequiredParams: []string{},
		ExtraParams:    []string{"autoupgrade", "availabilityzone", "backupretention", "backupwindow", "cluster", "copytagstosnapshot", "dbname", "dbsecuritygroups", "domain", "encrypted", "engine", "iamrole", "id", "iops", "license", "maintenancewindow", "multiaz", "optiongroup", "parametergroup", "password", "port", "public", "replica", "replica-source", "size", "storagetype", "subnetgroup", "timezone", "type", "username", "version", "vpcsecuritygroups"},
	},
	"createdbsubnetgroup": {
		Action:         "create",
		Entity:         "dbsubnetgroup",
		Api:            "rds",
		RequiredParams: []string{},
		ExtraParams:    []string{"description", "name", "subnets"},
	},
	"createdistribution": {
		Action:         "create",
		Entity:         "distribution",
		Api:            "cloudfront",
		RequiredParams: []string{},
		ExtraParams:    []string{"certificate", "comment", "default-file", "domain-aliases", "enable", "forward-cookies", "forward-queries", "https-behaviour", "min-ttl", "origin-domain", "origin-path", "price-class"},
	},
	"createelasticip": {
		Action:         "create",
		Entity:         "elasticip",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"domain"},
	},
	"createfunction": {
		Action:         "create",
		Entity:         "function",
		Api:            "lambda",
		RequiredParams: []string{},
		ExtraParams:    []string{"bucket", "description", "handler", "memory", "name", "object", "objectversion", "publish", "role", "runtime", "timeout", "zipfile"},
	},
	"creategroup": {
		Action:         "create",
		Entity:         "group",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"createimage": {
		Action:         "create",
		Entity:         "image",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"description", "instance", "name", "reboot"},
	},
	"createinstance": {
		Action:         "create",
		Entity:         "instance",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"count", "distro", "image", "ip", "keypair", "lock", "name", "role", "securitygroup", "subnet", "type", "userdata"},
	},
	"createinstanceprofile": {
		Action:         "create",
		Entity:         "instanceprofile",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"createinternetgateway": {
		Action:         "create",
		Entity:         "internetgateway",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{},
	},
	"createkeypair": {
		Action:         "create",
		Entity:         "keypair",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"encrypted", "name"},
	},
	"createlaunchconfiguration": {
		Action:         "create",
		Entity:         "launchconfiguration",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"distro", "image", "keypair", "name", "public", "role", "securitygroups", "spotprice", "type", "userdata"},
	},
	"createlistener": {
		Action:         "create",
		Entity:         "listener",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"actiontype", "certificate", "loadbalancer", "port", "protocol", "sslpolicy", "targetgroup"},
	},
	"createloadbalancer": {
		Action:         "create",
		Entity:         "loadbalancer",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"iptype", "name", "scheme", "securitygroups", "subnet-mappings", "subnets", "type"},
	},
	"createloginprofile": {
		Action:         "create",
		Entity:         "loginprofile",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"password", "password-reset", "username"},
	},
	"createmfadevice": {
		Action:         "create",
		Entity:         "mfadevice",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"createnatgateway": {
		Action:         "create",
		Entity:         "natgateway",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"elasticip-id", "subnet"},
	},
	"createnetworkinterface": {
		Action:         "create",
		Entity:         "networkinterface",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"description", "privateip", "securitygroups", "subnet"},
	},
	"createpolicy": {
		Action:         "create",
		Entity:         "policy",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"action", "conditions", "description", "effect", "name", "resource"},
	},
	"createqueue": {
		Action:         "create",
		Entity:         "queue",
		Api:            "sqs",
		RequiredParams: []string{},
		ExtraParams:    []string{"delay", "max-msg-size", "msg-wait", "name", "policy", "redrive-policy", "retention-period", "visibility-timeout"},
	},
	"createrecord": {
		Action:         "create",
		Entity:         "record",
		Api:            "route53",
		RequiredParams: []string{},
		ExtraParams:    []string{"comment", "name", "ttl", "type", "value", "zone"},
	},
	"createrepository": {
		Action:         "create",
		Entity:         "repository",
		Api:            "ecr",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"createrole": {
		Action:         "create",
		Entity:         "role",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"conditions", "name", "principal-account", "principal-service", "principal-user", "sleep-after"},
	},
	"createroute": {
		Action:         "create",
		Entity:         "route",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"cidr", "gateway", "table"},
	},
	"createroutetable": {
		Action:         "create",
		Entity:         "routetable",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"vpc"},
	},
	"creates3object": {
		Action:         "create",
		Entity:         "s3object",
		Api:            "s3",
		RequiredParams: []string{},
		ExtraParams:    []string{"acl", "bucket", "file", "name"},
	},
	"createscalinggroup": {
		Action:         "create",
		Entity:         "scalinggroup",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"cooldown", "desired-capacity", "healthcheck-grace-period", "healthcheck-type", "launchconfiguration", "max-size", "min-size", "name", "new-instances-protected", "subnets", "targetgroups"},
	},
	"createscalingpolicy": {
		Action:         "create",
		Entity:         "scalingpolicy",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"adjustment-magnitude", "adjustment-scaling", "adjustment-type", "cooldown", "name", "scalinggroup"},
	},
	"createsecuritygroup": {
		Action:         "create",
		Entity:         "securitygroup",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"description", "name", "vpc"},
	},
	"createsnapshot": {
		Action:         "create",
		Entity:         "snapshot",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"description", "volume"},
	},
	"createstack": {
		Action:         "create",
		Entity:         "stack",
		Api:            "cloudformation",
		RequiredParams: []string{},
		ExtraParams:    []string{"capabilities", "disable-rollback", "name", "notifications", "on-failure", "parameters", "policy-file", "resource-types", "role", "stack-file", "tags", "template-file", "timeout"},
	},
	"createsubnet": {
		Action:         "create",
		Entity:         "subnet",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"availabilityzone", "cidr", "name", "public", "vpc"},
	},
	"createsubscription": {
		Action:         "create",
		Entity:         "subscription",
		Api:            "sns",
		RequiredParams: []string{},
		ExtraParams:    []string{"endpoint", "protocol", "topic"},
	},
	"createtag": {
		Action:         "create",
		Entity:         "tag",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"key", "resource", "value"},
	},
	"createtargetgroup": {
		Action:         "create",
		Entity:         "targetgroup",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"healthcheckinterval", "healthcheckpath", "healthcheckport", "healthcheckprotocol", "healthchecktimeout", "healthythreshold", "matcher", "name", "port", "protocol", "unhealthythreshold", "vpc"},
	},
	"createtopic": {
		Action:         "create",
		Entity:         "topic",
		Api:            "sns",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"createuser": {
		Action:         "create",
		Entity:         "user",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"createvolume": {
		Action:         "create",
		Entity:         "volume",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"availabilityzone", "size"},
	},
	"createvpc": {
		Action:         "create",
		Entity:         "vpc",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"cidr", "name"},
	},
	"createzone": {
		Action:         "create",
		Entity:         "zone",
		Api:            "route53",
		RequiredParams: []string{},
		ExtraParams:    []string{"callerreference", "comment", "delegationsetid", "isprivate", "name", "vpcid", "vpcregion"},
	},
	"deleteaccesskey": {
		Action:         "delete",
		Entity:         "accesskey",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "user"},
	},
	"deletealarm": {
		Action:         "delete",
		Entity:         "alarm",
		Api:            "cloudwatch",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deleteappscalingpolicy": {
		Action:         "delete",
		Entity:         "appscalingpolicy",
		Api:            "applicationautoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"dimension", "name", "resource", "service-namespace"},
	},
	"deleteappscalingtarget": {
		Action:         "delete",
		Entity:         "appscalingtarget",
		Api:            "applicationautoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"dimension", "resource", "service-namespace"},
	},
	"deletebucket": {
		Action:         "delete",
		Entity:         "bucket",
		Api:            "s3",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deletecertificate": {
		Action:         "delete",
		Entity:         "certificate",
		Api:            "acm",
		RequiredParams: []string{},
		ExtraParams:    []string{"arn"},
	},
	"deletecontainercluster": {
		Action:         "delete",
		Entity:         "containercluster",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletecontainertask": {
		Action:         "delete",
		Entity:         "containertask",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"all-versions", "name"},
	},
	"deletedatabase": {
		Action:         "delete",
		Entity:         "database",
		Api:            "rds",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "skip-snapshot", "snapshot"},
	},
	"deletedbsubnetgroup": {
		Action:         "delete",
		Entity:         "dbsubnetgroup",
		Api:            "rds",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deletedistribution": {
		Action:         "delete",
		Entity:         "distribution",
		Api:            "cloudfront",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deleteelasticip": {
		Action:         "delete",
		Entity:         "elasticip",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "ip"},
	},
	"deletefunction": {
		Action:         "delete",
		Entity:         "function",
		Api:            "lambda",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "version"},
	},
	"deletegroup": {
		Action:         "delete",
		Entity:         "group",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deleteimage": {
		Action:         "delete",
		Entity:         "image",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"delete-snapshots", "id"},
	},
	"deleteinstance": {
		Action:         "delete",
		Entity:         "instance",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"ids"},
	},
	"deleteinstanceprofile": {
		Action:         "delete",
		Entity:         "instanceprofile",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deleteinternetgateway": {
		Action:         "delete",
		Entity:         "internetgateway",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletekeypair": {
		Action:         "delete",
		Entity:         "keypair",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deletelaunchconfiguration": {
		Action:         "delete",
		Entity:         "launchconfiguration",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deletelistener": {
		Action:         "delete",
		Entity:         "listener",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deleteloadbalancer": {
		Action:         "delete",
		Entity:         "loadbalancer",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deleteloginprofile": {
		Action:         "delete",
		Entity:         "loginprofile",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"username"},
	},
	"deletemfadevice": {
		Action:         "delete",
		Entity:         "mfadevice",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletenatgateway": {
		Action:         "delete",
		Entity:         "natgateway",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletenetworkinterface": {
		Action:         "delete",
		Entity:         "networkinterface",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletepolicy": {
		Action:         "delete",
		Entity:         "policy",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"all-versions", "arn"},
	},
	"deletequeue": {
		Action:         "delete",
		Entity:         "queue",
		Api:            "sqs",
		RequiredParams: []string{},
		ExtraParams:    []string{"url"},
	},
	"deleterecord": {
		Action:         "delete",
		Entity:         "record",
		Api:            "route53",
		RequiredParams: []string{},
		ExtraParams:    []string{"name", "ttl", "type", "value", "zone"},
	},
	"deleterepository": {
		Action:         "delete",
		Entity:         "repository",
		Api:            "ecr",
		RequiredParams: []string{},
		ExtraParams:    []string{"account", "force", "name"},
	},
	"deleterole": {
		Action:         "delete",
		Entity:         "role",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deleteroute": {
		Action:         "delete",
		Entity:         "route",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"cidr", "table"},
	},
	"deleteroutetable": {
		Action:         "delete",
		Entity:         "routetable",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletes3object": {
		Action:         "delete",
		Entity:         "s3object",
		Api:            "s3",
		RequiredParams: []string{},
		ExtraParams:    []string{"bucket", "name"},
	},
	"deletescalinggroup": {
		Action:         "delete",
		Entity:         "scalinggroup",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"force", "name"},
	},
	"deletescalingpolicy": {
		Action:         "delete",
		Entity:         "scalingpolicy",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletesecuritygroup": {
		Action:         "delete",
		Entity:         "securitygroup",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletesnapshot": {
		Action:         "delete",
		Entity:         "snapshot",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletestack": {
		Action:         "delete",
		Entity:         "stack",
		Api:            "cloudformation",
		RequiredParams: []string{},
		ExtraParams:    []string{"name", "retain-resources"},
	},
	"deletesubnet": {
		Action:         "delete",
		Entity:         "subnet",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletesubscription": {
		Action:         "delete",
		Entity:         "subscription",
		Api:            "sns",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletetag": {
		Action:         "delete",
		Entity:         "tag",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"key", "resource", "value"},
	},
	"deletetargetgroup": {
		Action:         "delete",
		Entity:         "targetgroup",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletetopic": {
		Action:         "delete",
		Entity:         "topic",
		Api:            "sns",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deleteuser": {
		Action:         "delete",
		Entity:         "user",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"name"},
	},
	"deletevolume": {
		Action:         "delete",
		Entity:         "volume",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletevpc": {
		Action:         "delete",
		Entity:         "vpc",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"deletezone": {
		Action:         "delete",
		Entity:         "zone",
		Api:            "route53",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"detachalarm": {
		Action:         "detach",
		Entity:         "alarm",
		Api:            "cloudwatch",
		RequiredParams: []string{},
		ExtraParams:    []string{"action-arn", "name"},
	},
	"detachcontainertask": {
		Action:         "detach",
		Entity:         "containertask",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"container-name", "name"},
	},
	"detachelasticip": {
		Action:         "detach",
		Entity:         "elasticip",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"association"},
	},
	"detachinstance": {
		Action:         "detach",
		Entity:         "instance",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "targetgroup"},
	},
	"detachinstanceprofile": {
		Action:         "detach",
		Entity:         "instanceprofile",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"instance", "name"},
	},
	"detachinternetgateway": {
		Action:         "detach",
		Entity:         "internetgateway",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "vpc"},
	},
	"detachmfadevice": {
		Action:         "detach",
		Entity:         "mfadevice",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "user"},
	},
	"detachnetworkinterface": {
		Action:         "detach",
		Entity:         "networkinterface",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"attachment", "force", "id", "instance"},
	},
	"detachpolicy": {
		Action:         "detach",
		Entity:         "policy",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"arn", "group", "role", "user"},
	},
	"detachrole": {
		Action:         "detach",
		Entity:         "role",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"instanceprofile", "name"},
	},
	"detachroutetable": {
		Action:         "detach",
		Entity:         "routetable",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"association"},
	},
	"detachsecuritygroup": {
		Action:         "detach",
		Entity:         "securitygroup",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "instance"},
	},
	"detachuser": {
		Action:         "detach",
		Entity:         "user",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"group", "name"},
	},
	"detachvolume": {
		Action:         "detach",
		Entity:         "volume",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"device", "force", "id", "instance"},
	},
	"importimage": {
		Action:         "import",
		Entity:         "image",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"architecture", "bucket", "description", "license", "platform", "role", "s3object", "snapshot", "url"},
	},
	"startalarm": {
		Action:         "start",
		Entity:         "alarm",
		Api:            "cloudwatch",
		RequiredParams: []string{},
		ExtraParams:    []string{"names"},
	},
	"startcontainertask": {
		Action:         "start",
		Entity:         "containertask",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"cluster", "deployment-name", "desired-count", "loadbalancer.container-name", "loadbalancer.container-port", "loadbalancer.targetgroup", "name", "role", "type"},
	},
	"startdatabase": {
		Action:         "start",
		Entity:         "database",
		Api:            "rds",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"startinstance": {
		Action:         "start",
		Entity:         "instance",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"stopalarm": {
		Action:         "stop",
		Entity:         "alarm",
		Api:            "cloudwatch",
		RequiredParams: []string{},
		ExtraParams:    []string{"names"},
	},
	"stopcontainertask": {
		Action:         "stop",
		Entity:         "containertask",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"cluster", "deployment-name", "run-arn", "type"},
	},
	"stopdatabase": {
		Action:         "stop",
		Entity:         "database",
		Api:            "rds",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"stopinstance": {
		Action:         "stop",
		Entity:         "instance",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id"},
	},
	"updatebucket": {
		Action:         "update",
		Entity:         "bucket",
		Api:            "s3",
		RequiredParams: []string{},
		ExtraParams:    []string{"acl", "enforce-https", "index-suffix", "name", "public-website", "redirect-hostname"},
	},
	"updatecontainertask": {
		Action:         "update",
		Entity:         "containertask",
		Api:            "ecs",
		RequiredParams: []string{},
		ExtraParams:    []string{"cluster", "deployment-name", "desired-count", "name"},
	},
	"updatedistribution": {
		Action:         "update",
		Entity:         "distribution",
		Api:            "cloudfront",
		RequiredParams: []string{},
		ExtraParams:    []string{"certificate", "comment", "default-file", "domain-aliases", "enable", "forward-cookies", "forward-queries", "https-behaviour", "id", "min-ttl", "origin-domain", "origin-path", "price-class"},
	},
	"updateimage": {
		Action:         "update",
		Entity:         "image",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"accounts", "description", "groups", "id", "operation", "product-codes"},
	},
	"updateinstance": {
		Action:         "update",
		Entity:         "instance",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "lock", "type"},
	},
	"updateloginprofile": {
		Action:         "update",
		Entity:         "loginprofile",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"password", "password-reset", "username"},
	},
	"updatepolicy": {
		Action:         "update",
		Entity:         "policy",
		Api:            "iam",
		RequiredParams: []string{},
		ExtraParams:    []string{"action", "arn", "conditions", "effect", "resource"},
	},
	"updaterecord": {
		Action:         "update",
		Entity:         "record",
		Api:            "route53",
		RequiredParams: []string{},
		ExtraParams:    []string{"name", "ttl", "type", "value", "zone"},
	},
	"updates3object": {
		Action:         "update",
		Entity:         "s3object",
		Api:            "s3",
		RequiredParams: []string{},
		ExtraParams:    []string{"acl", "bucket", "name", "version"},
	},
	"updatescalinggroup": {
		Action:         "update",
		Entity:         "scalinggroup",
		Api:            "autoscaling",
		RequiredParams: []string{},
		ExtraParams:    []string{"cooldown", "desired-capacity", "healthcheck-grace-period", "healthcheck-type", "launchconfiguration", "max-size", "min-size", "name", "new-instances-protected", "subnets"},
	},
	"updatesecuritygroup": {
		Action:         "update",
		Entity:         "securitygroup",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"cidr", "id", "inbound", "outbound", "portrange", "protocol", "securitygroup"},
	},
	"updatestack": {
		Action:         "update",
		Entity:         "stack",
		Api:            "cloudformation",
		RequiredParams: []string{},
		ExtraParams:    []string{"capabilities", "name", "notifications", "parameters", "policy-file", "policy-update-file", "resource-types", "role", "stack-file", "tags", "template-file", "use-previous-template"},
	},
	"updatesubnet": {
		Action:         "update",
		Entity:         "subnet",
		Api:            "ec2",
		RequiredParams: []string{},
		ExtraParams:    []string{"id", "public"},
	},
	"updatetargetgroup": {
		Action:         "update",
		Entity:         "targetgroup",
		Api:            "elbv2",
		RequiredParams: []string{},
		ExtraParams:    []string{"deregistrationdelay", "healthcheckinterval", "healthcheckpath", "healthcheckport", "healthcheckprotocol", "healthchecktimeout", "healthythreshold", "id", "matcher", "stickiness", "stickinessduration", "unhealthythreshold"},
	},
}

var DriverSupportedActions = map[string][]string{
	"attach":       {"alarm", "containertask", "elasticip", "instance", "instanceprofile", "internetgateway", "mfadevice", "networkinterface", "policy", "role", "routetable", "securitygroup", "user", "volume"},
	"authenticate": {"registry"},
	"check":        {"certificate", "database", "distribution", "instance", "loadbalancer", "natgateway", "networkinterface", "scalinggroup", "securitygroup", "volume"},
	"copy":         {"image", "snapshot"},
	"create":       {"accesskey", "alarm", "appscalingpolicy", "appscalingtarget", "bucket", "certificate", "containercluster", "database", "dbsubnetgroup", "distribution", "elasticip", "function", "group", "image", "instance", "instanceprofile", "internetgateway", "keypair", "launchconfiguration", "listener", "loadbalancer", "loginprofile", "mfadevice", "natgateway", "networkinterface", "policy", "queue", "record", "repository", "role", "route", "routetable", "s3object", "scalinggroup", "scalingpolicy", "securitygroup", "snapshot", "stack", "subnet", "subscription", "tag", "targetgroup", "topic", "user", "volume", "vpc", "zone"},
	"delete":       {"accesskey", "alarm", "appscalingpolicy", "appscalingtarget", "bucket", "certificate", "containercluster", "containertask", "database", "dbsubnetgroup", "distribution", "elasticip", "function", "group", "image", "instance", "instanceprofile", "internetgateway", "keypair", "launchconfiguration", "listener", "loadbalancer", "loginprofile", "mfadevice", "natgateway", "networkinterface", "policy", "queue", "record", "repository", "role", "route", "routetable", "s3object", "scalinggroup", "scalingpolicy", "securitygroup", "snapshot", "stack", "subnet", "subscription", "tag", "targetgroup", "topic", "user", "volume", "vpc", "zone"},
	"detach":       {"alarm", "containertask", "elasticip", "instance", "instanceprofile", "internetgateway", "mfadevice", "networkinterface", "policy", "role", "routetable", "securitygroup", "user", "volume"},
	"import":       {"image"},
	"start":        {"alarm", "containertask", "database", "instance"},
	"stop":         {"alarm", "containertask", "database", "instance"},
	"update":       {"bucket", "containertask", "distribution", "image", "instance", "loginprofile", "policy", "record", "s3object", "scalinggroup", "securitygroup", "stack", "subnet", "targetgroup"},
}
